lesson.20/my-shop/app.py
from flask import Flask, request, render_template

from views import product_app

app = Flask(__name__)
app.register_blueprint(product_app, url_prefix="/products")


@app.route("/", methods=["GET", "POST"])
def index():
    name = "World"
    if request.method == "POST":
        name = request.form.get('name', 'World')
    return render_template("index.html", name=name)


# app.add_url_rule("/", "index", index)
# app.add_url_rule("/", view_func=index)

@app.route("/hello/")
@app.route("/hello/<string:name>/")
def hello(name=None):
    if name is None:
        name = "World"
    return f"<h1>Hello {name}!</h1>"


# @app.route('/post/<string:post_id>/')
# def alternative_show_post(post_id):
#     post_id > 0
#     return 'Post (str) %r' % post_id


@app.route('/post/<int:post_id>/')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post int %d' % post_id

lesson.20/my-shop/views/product.py
from flask import Blueprint, render_template, request, jsonify
from werkzeug.exceptions import BadRequest

product_app = Blueprint("product_app", __name__)


PRODUCTS = {
    1: 'Smartphone',
    2: 'Tablet',
    3: 'Laptop',
}


@product_app.route("/")
def product_list():
    return render_template("products/index.html", products=PRODUCTS)


@product_app.route("/<int:product_id>/", methods=['GET', 'DELETE'])
def product_detail(product_id: int):
    try:
        product_name = PRODUCTS[product_id]
    except KeyError:
        raise BadRequest(f"Invalid product id #{product_id}")

    if request.method == 'DELETE':
        PRODUCTS.pop(product_id)
        return jsonify(ok=True)

    return render_template(
        "products/detail.html",
        product_id=product_id,
        product_name=product_name,
    )

lesson.20/my-shop/templates/products/detail.html
{% extends 'base.html' %}

{% block title -%}
  Product #{{ product_id }}
{%- endblock %}

{% block body %}
  <h1>Product <code id="product-name">{{ product_name }}</code></h1>
  <hr>
  <a href="{{ url_for('product_app.product_list') }}">Product list</a>

  <hr>
{#  Admin area #}
  <div>
    <button id="delete-product" class="btn btn-danger btn-lg">Delete</button>
  </div>
{% endblock %}

{% block after_body %}
  <script>
  $(function() {
    const name = $('#product-name')
    console.log(name.text())

    $('#delete-product').click(function () {
      $.ajax({
        method: 'DELETE',
        success: function (res) {
          console.log(res)
          console.log(res.data)
        },
        error: function (err) {
          console.error(err)
        },
        complete: function () {
          window.location = '{{ url_for('product_app.product_list') }}'
        },
      })
    })
  });
  </script>
{% endblock %}

lesson.20/my-shop/templates/products/index.html
{% extends 'base.html' %}

{% block title -%}
  Products
{%- endblock %}

{% block body %}
  <h1>Products list</h1>
  <div class="alert alert-info" role="alert">
    Sale only today!
  </div>
  <div class="row">
    <div class="col col-12 col-md-8 col-lg-6 col-xl-4">
      <ul class="list-group">
        {% for product_id in products %}
          <li class="list-group-item product-item">
            <a class="my-2" href="{{ url_for('product_app.product_detail', product_id=product_id) }}">
              {{ products[product_id] }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block after_body %}
  <script>
    $(function () {
      const productItems = $('.product-item')
      console.log(productItems)
    });
  </script>
{% endblock %}